name: TiKV-CDC
on:
  push:
    branches: main
    paths: cdc/**
  pull_request:
    branches: main
    paths: cdc/**

permissions:
  contents: read

env:
  GO_VERSION: 1.21.4

jobs:
  cdc-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: make check
        shell: bash
        run: |
          cd cdc/
          make check
  cdc-check-gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: make check-gosec
        shell: bash
        run: |
          cd cdc/
          make check-gosec
  cdc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: make cdc
        shell: bash
        run: |
          cd cdc/
          make cdc
